---
- hosts: Prod
  become: true
  become_user: root
  tasks:
          - name: Shutdown CentOS Systems
            command: poweroff
            when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"
